image: ruby:2.4.6

pipelines:
  default:
    - step:
        caches:
          - bundler
        script: # Modify the commands below to build your repository.
          - gem install bundler
          - bundle install
          - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.2
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              APPLICATION_NAME: 'ethu-gamedb-app'
              VERSION_LABEL: 'deploy-$BITBUCKET_BUILD_NUMBER-multiple'
              ZIP_FILE: 'gamedb-application.zip'
              ENVIRONMENT_NAME: 'production'
              WAIT: 'true'
definitions:
  caches:
    bundler: ./vendor
