development:
  host: 'localhost'
  port: '6379'
test:
  host: 'localhost'
  port: '6379'
production:
  #host: 'ethugamedb-redis-server.xadimb.ng.0001.usw2.cache.amazonaws.com'
  host: 'redis://h:pac680b3c0e990891e6b1678f92ce2307cb649d1ab15bde94007529ad7f522454@ec2-54-160-97-168.compute-1.amazonaws.com:14949'
  port: '10097'